### PR TITLE
merging Chris' branch

### PR DESCRIPTION
**Pull request by ChrisTofuLee**
created github team for project, testing merging of branch

### CODE REVIEW

**Comment by hyperkarmic** [comment]
Awesome - nice work!!!!!!

**Review by hyperkarmic — DISMISSED** [review]
changes reviewed!!!!!!

**Review by Nuelthesupreme — APPROVED** [review]

**Review by Nuelthesupreme — APPROVED** [review]

**Review by Nuelthesupreme — DISMISSED** [review]

**Review by andrewroar — DISMISSED** [review]
yes

**Review by hyperkarmic — APPROVED** [review]
Hopefully the conflicts are solved!!!! :)

**Review by Nuelthesupreme — APPROVED** [review]

**Review by andrewroar — APPROVED** [review]
yes

**Review by andrewroar — APPROVED** [review]

**Pull request merged**
