### PR TITLE
add name to read me

### PR DESCRIPTION
**Pull request by hyperkarmic**
my name added to read me!

### CODE REVIEW

**Review by ChrisTofuLee — COMMENTED** [review]
kl

**Review by ChrisTofuLee — DISMISSED** [review]

**Review by andrewroar — APPROVED** [review]
yes

**Review by andrewroar — APPROVED** [review]
yes

**Review by andrewroar — APPROVED** [review]
yes

**Review by andrewroar — DISMISSED** [review]
yes

**Review by andrewroar — APPROVED** [review]

**Review by Nuelthesupreme — APPROVED** [review]

**Review by Nuelthesupreme — APPROVED** [review]

**Review by ChrisTofuLee — APPROVED** [review]
looks good

**Pull request merged**
